### ISSUE TITLE
Accelerometer Readings: X are constant & don't change

### ISSUE THREAD

**Issue by naimaryan1** [polarpiberry/MPU6050-C-CPP-Library-for-Raspberry-Pi#11]
All values from accelerometer y,z & gyro x,y,z change as expected when the MPU6050 is moved, except the accelerometer X values. 

This is reproducible in the original "Example.cpp" that is provided by the repo:
![image](https://github.com/alex-mous/MPU6050-C-CPP-Library-for-Raspberry-Pi/assets/7257500/cab87cc0-0c90-4280-8fbe-0d44d58d5e8f)

I was also able to replicate this odd behavior via my own code:

![image](https://github.com/alex-mous/MPU6050-C-CPP-Library-for-Raspberry-Pi/assets/7257500/71c2d834-d1ec-417b-a39b-f312045a452e)

Im running the code on Raspberri Pi Zero W, with OS:

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"

Please look into this bug.

**Comment by alex-mous** [comment]
This is likely a hardware issue if you replicated it with your own code/another library. I recall having a similar issue once - perhaps try resetting the sensor if possible? 

Please reopen this if the problem is only reproducible using this library and I’ll take another look, but this is difficult for me to debug as the sensors themselves can be fickle.

Hope this helps
